### PR TITLE
Upgrade to SS4

### PR DESCRIPTION
**Pull request by gordonbanderson**
hi

I've updated this module to SilverStripe 4, and added continuous integration.  One test is failing with Postgresql, not sure why.  You will also need to change the paths of the badges and activate the relevant services yourself (or remove the badges)

Cheers

Gordon

PS Lots of commits, probably best you squash them

### CODE REVIEW

**Comment by lekoala** [comment]
wow great work. thanks a lot. i'll merge it as is and check on my side later :-)

**Comment by gordonbanderson** [comment]
You will need to update the badges, otherwise they will be pointing at my pull request branch for ever more ;)   Thanks for the merge.

**Comment by lekoala** [comment]
yes done!

**Comment by gordonbanderson** [comment]
cool :)

**Pull request merged**
